Repository flomesh-io/ErieCanal, pull requests merged in 2022-12, with the labels that each got.

#9 feat: prepare prerelease v0.1.0-alpha.1
  VERSION
  charts/erie-canal/Chart.lock
  charts/erie-canal/Chart.yaml
  charts/namespaced-ingress/Chart.lock
  charts/namespaced-ingress/Chart.yaml
  charts/tpls/Chart.yaml
Labels: enhancement

#15 Added CONTRIBUTING document
  CONTRIBUTING.md
Labels: documentation

#18 refactor: root element of helm chart
  README.md
  charts/erie-canal/README.md
  charts/erie-canal/templates/crds-configmap.yaml
  charts/erie-canal/templates/egress-gateway-configmap.yaml
  charts/erie-canal/templates/egress-gateway-deployment.yaml
  charts/erie-canal/templates/egress-gateway-service.yaml
  charts/erie-canal/templates/fsm-manager-service.yaml
  charts/erie-canal/templates/fsm-role.yaml
  charts/erie-canal/templates/fsm-rolebinding.yaml
  charts/erie-canal/templates/ingress-class.yaml
  charts/erie-canal/templates/ingress-pipy-deployment.yaml
  charts/erie-canal/templates/ingress-pipy-service.yaml
  charts/erie-canal/templates/ingress-repo.yaml
  charts/erie-canal/templates/leader-election-role.yaml
  charts/erie-canal/templates/leader-election-rolebinding.yaml
  charts/erie-canal/templates/manager-configmap.yaml
  charts/erie-canal/templates/manager-deployment.yaml
  charts/erie-canal/templates/manifests-configmap.yaml
  charts/erie-canal/templates/mesh-config-configmap.yaml
  charts/erie-canal/templates/mesh-config-role.yaml
  charts/erie-canal/templates/mutating-webhook-configuration.yaml
  charts/erie-canal/templates/pre-delete.yaml
  charts/erie-canal/templates/repo-deployment.yaml
  charts/erie-canal/templates/repo-init-scripts-configmap.yaml
  charts/erie-canal/templates/repo-service.yaml
  charts/erie-canal/templates/serviceaccount.yaml
  charts/erie-canal/templates/validating-webhook-configuration.yaml
  charts/erie-canal/templates/webhook-service.yaml
  charts/erie-canal/values.schema.json
  charts/erie-canal/values.yaml
  charts/namespaced-ingress/templates/_helpers.tpl
  charts/namespaced-ingress/templates/deployment.yaml
  charts/namespaced-ingress/templates/role.yaml
  charts/namespaced-ingress/templates/rolebinding.yaml
  charts/namespaced-ingress/templates/service.yaml
  charts/namespaced-ingress/templates/serviceaccount.yaml
  charts/tpls/templates/_envs.tpl
  charts/tpls/templates/_images.tpl
  charts/tpls/templates/_labels.tpl
  charts/tpls/templates/_names.tpl
  charts/tpls/templates/_services.tpl
  controllers/namespacedingress/v1alpha1/namespacedingress_controller.go
  hack/generate-deploy.sh
  samples/setup/readme.md
Labels: refactor

#19 feat: add more print columns for ServiceExport
  apis/serviceexport/v1alpha1/serviceexport_types.go
  charts/erie-canal/apis/flomesh.io_mcs-api.yaml
Labels: enhancement
