Repository flomesh-io/ErieCanal, pull requests merged in 2023-03, with the labels that each got.

#72 update: README.md architecture section
  README.md
  ec-mesh-architecture.png
Labels: documentation

#74 fix: validation issue of GlobalTrafficPolicy
  go.mod
  pkg/webhooks/globaltrafficpolicy/webhook.go
Labels: bug

#75 feat: add short name for MCS APIs
  apis/globaltrafficpolicy/v1alpha1/types.go
  apis/serviceexport/v1alpha1/serviceexport_types.go
  apis/serviceimport/v1alpha1/serviceimport_types.go
  charts/erie-canal/apis/flomesh.io_mcs-api.yaml
Labels: enhancement
