Repository flomesh-io/ErieCanal, pull requests merged in 2023-01, with the labels that each got.

#24 build: use distroless:base-nossl-debian11 as base image of ingress-pipy
  dockerfiles/ingress-pipy/Dockerfile
Labels: enhancement, security

#29 feat: enhance helm chart uninstallation
  README.md
  VERSION
  charts/erie-canal/Chart.lock
  charts/erie-canal/Chart.yaml
  charts/erie-canal/templates/pre-delete.yaml
  charts/namespaced-ingress/Chart.lock
  charts/namespaced-ingress/Chart.yaml
  charts/tpls/Chart.yaml
  samples/setup/readme.md
Labels: enhancement

#35 Fix: demo script check_command
  docs/demo/up.sh
Labels: bug

#36 feat: session sticky
  charts/erie-canal/components/scripts.tar.gz
  charts/erie-canal/components/scripts/ingress/plugins/balancer.js
Labels: enhancement

#37 feat: pod hardening
  README.md
  VERSION
  charts/erie-canal/Chart.lock
  charts/erie-canal/Chart.yaml
  charts/erie-canal/templates/egress-gateway-deployment.yaml
  charts/erie-canal/templates/ingress-class.yaml
  charts/erie-canal/templates/ingress-pipy-deployment.yaml
  charts/erie-canal/templates/manager-deployment.yaml
  charts/erie-canal/templates/mesh-config-configmap.yaml
  charts/erie-canal/templates/repo-deployment.yaml
  charts/erie-canal/values.yaml
  charts/namespaced-ingress/Chart.lock
  charts/namespaced-ingress/Chart.yaml
  charts/tpls/Chart.yaml
  samples/session-sticky/001.yaml
  samples/setup/readme.md
Labels: enhancement

#42 build: build debug-nonroot image for development
  dockerfiles/ingress-pipy/Dockerfile
Labels: enhancement

#43 fix: pipy crash when codebase reloading
  charts/erie-canal/components/scripts.tar.gz
  charts/erie-canal/components/scripts/ingress/plugins/balancer.js
  charts/erie-canal/components/scripts/ingress/plugins/default.js
  charts/erie-canal/components/scripts/ingress/plugins/reject-http.js
  charts/erie-canal/components/scripts/ingress/plugins/router.js
Labels: bug

#44 fix: a typo in shell script
  docs/demo/flomesh.sh
Labels: documentation

#45 fix: typo and robust improvement
  charts/erie-canal/templates/ingress-pipy-deployment.yaml
  charts/erie-canal/templates/ingress-pipy-service.yaml
  charts/erie-canal/templates/repo-deployment.yaml
  charts/erie-canal/values.schema.json
  charts/erie-canal/values.yaml
  charts/tpls/templates/_services.tpl
  dockerfiles/ingress-pipy/Dockerfile
  pkg/config/store.go
  samples/ingress/300-ingress-tls.yaml
  samples/mTLS-ingress/extfile.cnf
  samples/mTLS-ingress/gen-certs.sh
  samples/mTLS-ingress/values.yaml
  samples/multi-cluster/001-pipy-deployment.yaml
  samples/session-sticky/001.yaml
Labels: enhancement

#48 feat: enhance NamespacedIngress API
  README.md
  VERSION
  apis/namespacedingress/v1alpha1/namespacedingress_types.go
  apis/namespacedingress/v1alpha1/zz_generated.deepcopy.go
  charts/erie-canal/Chart.lock
  charts/erie-canal/Chart.yaml
  charts/erie-canal/apis/flomesh.io_namespacedingresses.yaml
  charts/namespaced-ingress/Chart.lock
  charts/namespaced-ingress/Chart.yaml
  charts/namespaced-ingress/templates/_helpers.tpl
  charts/namespaced-ingress/templates/deployment.yaml
  charts/namespaced-ingress/templates/service.yaml
  charts/tpls/Chart.yaml
  charts/tpls/templates/_services.tpl
  samples/setup/readme.md
Labels: enhancement

#49 build: bump pipy version to 0.90.0-18
  README.md
  VERSION
  charts/erie-canal/Chart.lock
  charts/erie-canal/Chart.yaml
  charts/erie-canal/values.schema.json
  charts/erie-canal/values.yaml
  charts/namespaced-ingress/Chart.lock
  charts/namespaced-ingress/Chart.yaml
  charts/tpls/Chart.yaml
  dockerfiles/ingress-pipy/Dockerfile
  samples/ingress/300-ingress-tls.yaml
  samples/multi-cluster/001-pipy-deployment.yaml
  samples/session-sticky/001.yaml
  samples/setup/readme.md
Labels: dependencies

#50 feat: ingress leverages pipy multi-threads feature
  README.md
  VERSION
  charts/erie-canal/Chart.lock
  charts/erie-canal/Chart.yaml
  charts/namespaced-ingress/Chart.lock
  charts/namespaced-ingress/Chart.yaml
  charts/tpls/Chart.yaml
  cmd/ingress-pipy/main.go
  samples/setup/readme.md
Labels: enhancement
